version: "3.1"
services:
    database:
        container_name: mysql_database
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - mysql-db:/var/lib/mysql
        networks:
            - default
    www:
        container_name: apache_webserver
        build: .
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - database
        networks:
            - default
    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - database
        image: phpmyadmin
        links:
            - database:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    mysql-db:
